version: '3'
services:
  discovery:
    build:
      context: ./discovery
    ports:
      - "5000:5000"
    networks:
      static-network:
        ipv4_address: 172.20.0.5

  account:
    build:
      context: ./account-service
    ports:
      - "5001:5000"
    depends_on:
      - discovery
    environment:
      - SERVICE_NAME=account_service
      - DISCOVERY_URL=http://discovery:5000/register
      - SERVICE_URL=http://172.20.0.6
      - PORT=5000
    networks:
      static-network:
        ipv4_address: 172.20.0.6

  cart:
    build:
      context: ./cart-service
    ports:
      - "5002:5000"
    depends_on:
      - discovery
    environment:
      - SERVICE_NAME=cart_service
      - DISCOVERY_URL=http://discovery:5000/register
      - SERVICE_URL=http://172.20.0.7
      - PORT=5000

    networks:
      static-network:
        ipv4_address: 172.20.0.7


networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16






