"""make cart many-to-many

Revision ID: 8e174bcdf1d3
Revises: ca7fae2a8f1d
Create Date: 2023-07-24 02:03:50.408261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e174bcdf1d3'
down_revision = 'ca7fae2a8f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebook_cart',
    sa.Column('ebook_id', sa.Integer(), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['ebook_id'], ['ebook.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebook_cart')
    # ### end Alembic commands ###
