"""empty message

Revision ID: ca7fae2a8f1d
Revises: d13d2af512e3
Create Date: 2023-07-24 01:37:56.945683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7fae2a8f1d'
down_revision = 'd13d2af512e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebook_library',
    sa.Column('ebook_id', sa.Integer(), nullable=True),
    sa.Column('user_library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ebook_id'], ['ebook.id'], ),
    sa.ForeignKeyConstraint(['user_library_id'], ['user_library.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebook_library')
    # ### end Alembic commands ###
