"""add price to ebook

Revision ID: d13d2af512e3
Revises: b6145f544ea9
Create Date: 2023-07-21 10:41:42.762010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13d2af512e3'
down_revision = 'b6145f544ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.drop_column('price_cents')

    # ### end Alembic commands ###
